#!/usr/bin/env node
// Embeds packs/*.ctx into src/generated/packs.ts so a bundled plugin carries its style packs.
// `--check` fails when the generated file is stale, for CI.
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const packsDir = join(root, 'packs');
const out = join(root, 'src', 'generated', 'packs.ts');
const files = readdirSync(packsDir).filter((f) => f.endsWith('.ctx')).sort();
const entries = files.map((f) => `  ${JSON.stringify(f.replace(/\.ctx$/, ''))}: ${JSON.stringify(readFileSync(join(packsDir, f), 'utf8'))},`);
const text = `// Generated by scripts/gen-packs.mjs from packs/*.ctx. Do not edit; run npm run gen:packs.\nexport const EMBEDDED_PACKS: Record<string, string> = {\n${entries.join('\n')}\n};\n`;

if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== text) { console.error('src/generated/packs.ts is stale; run npm run gen:packs'); process.exit(1); }
  console.log('packs module is current');
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text, 'utf8');
  console.log(`wrote ${out} (${files.length} packs)`);
}
